### ISSUE TITLE
Annoying warning due to joblib

### ISSUE THREAD

**Issue by oterrier** [kermitt2/delft#103]
When delft is used as a library in another python application using a more recent version of scikit-learn (0.22.2 for example) an annoying FutureWarning is dispayed:
```
FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
```
This is due to the explicit
```
from sklearn.externals import joblib
```
in sequenceLabelling/preprocess.py

Wich should be replaced by
```
import joblib
```
And at the same time it could be interesting to bump the current version of scikit-learn to a more recent one (0.22.2 for example)

Best regards

Olivier

**Comment by oterrier** [comment]
Thx Luca !

**Comment by kermitt2** [comment]
joblib is now out ! :)
