### ISSUE TITLE
Command for saving the metrics in a file

### ISSUE THREAD

**Issue by MahmoudAliEng** [kermitt2/delft#118]
How I can save the metrics of trainings and testing in a specific file ?

**Comment by MahmoudAliEng** [comment]
I looked in the appropriate directory `data/models/sequenceLabelling/` and did find neither the trained model nor the metrics !!! Anyone can help me please ??

**Comment by lfoppiano** [comment]
The output will be shown on the screen, so you just redirect the output to a file.
