### ISSUE TITLE
Print minimal configuration information when running training or train/eval 

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/delft#129]
I wonder whether we should print minimal information about the model configuration at the beginning of training/evaluation or train_eval. 

I suggest the following: 
 - batch_size
 - max epoch
 - max_sequence_length

I wonder if printing the architecture schema at every run should be reduced to just the first time, e.g. for n-fold cross-validation

**Comment by kermitt2** [comment]
It could be useful when evaluating yes! 
We could ideally only print parameter values which are not set to their default value. 

About the printing of the architecture, it is produced by model.summary() which is always executed currently when creating a model (in the init model class in model.py). We could control the summary() with an additional parameter.

**Comment by lfoppiano** [comment]
The problem is that the default value depends a lot from the type of model, there is a set of Ifs which are not easy to read. I'd rather see the end results when I run the model (which is also useful when I save the log in text files). 

I also implemented the model.summary() to be triggered as normal for train/eval and only the first time for train_eval

**Comment by lfoppiano** [comment]
I think we can close this 🎉
