### ISSUE TITLE
Bad performance to produce ELMo embedding

### ISSUE THREAD

**Issue by SeanLee97** [kermitt2/delft#145]
In my setting: batch size = 128, max_sequence_length = 300. It really takes time to produce the ELMo embedding, about 3s per batch. Is this a normal time?

**Comment by SeanLee97** [comment]
I have solved this problem. This is because my mounted driver has a poor writing speed rate. When I set `cache-training: false`, the problem was solved.

**Comment by kermitt2** [comment]
Using the ELMo embedding cache makes sense only with good SSD indeed.
