### ISSUE TITLE
Hardcoded padding tokens

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/delft#151]
I've noticed that the label to pad is hard-coded and in certain tokenizer it may be different (e.g. `<s>`). 

For example  (preprocess.py:343 and few other places below):

```
label_ids.append("<PAD>")
```

perhaps we should change it as:

```
label_ids.append(self.tokenizer.pad_token)
```

This was found when investigating #150 , I'm asking because I'm not 100% sure this is actually a problem.

**Comment by kermitt2** [comment]
Hi @lfoppiano !

This <PAD> here is just a empty label id because it corresponds to a subtoken ("empty" labels are assigned to special tokens and subtokens introduced by the tokenizer). The labels are not related to the tokenizer, so we should not use self.tokenizer.pad_token.

**Comment by kermitt2** [comment]
See also https://github.com/kermitt2/delft/issues/150#issuecomment-1382290023 for more details.

**Comment by lfoppiano** [comment]
Thanks for the clarification! 
I close this, we can eventually comment in #150
