### ISSUE TITLE
I am trying to make a model that reads problems and solutions and then it will generate text (when I give it a problem it will give the solutions) but i am stuck 

### ISSUE THREAD

**Issue by raneem199** [kermitt2/delft#159]
![1](https://user-images.githubusercontent.com/130366984/230898475-c717d841-0751-4e41-a543-9d6febf2a81a.jpg)
![2](https://user-images.githubusercontent.com/130366984/230898477-33f41247-09a0-4a2f-85a7-be9c57bb5e7b.jpg)
![3](https://user-images.githubusercontent.com/130366984/230898479-58e06058-6581-41f9-89d3-06347744c735.jpg)
![4](https://user-images.githubusercontent.com/130366984/230898481-e61f772f-8fa7-44c9-894d-087a7c50b166.jpg)

**Comment by raneem199** [comment]
what shall I do ??

**Comment by kermitt2** [comment]
Hello @raneem199 !

Your task is a question answering task, not related to this library, which is dedicated to sequence labeling and classification. 

A good start is for example https://huggingface.co/docs/transformers/tasks/question_answering

Good luck !
