### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by HaniehP** [kermitt2/delft#17]
The first time that I run the program, it builds the mdb files. However, after creation of these files, it fails to continue as it cannot allocate enough memory for the rest. The memory issue does not happen if .mdb files already exist.
I was wondering how much memory mdb creation requires?
I am running your code on some linux servers with 180GB shared RAM.

**Comment by kermitt2** [comment]
Thanks! Which program are you running and with which embeddings? 

In principle creating the lmdb database requires a very small amount of memory, just enough to read one line of embeddings file at the time, so we are really in the order of a few KB. 

Training on the other hand require a lot of memory, depending on the models. Are you using a GPU?

**Comment by HaniehP** [comment]
I am running:
nerTagger.py --dataset-type conll2003 --use-ELMo train_eval
using ELMo 1024d and GloVe 300d. (I downloaded them from the links you provided).
I don't use a GPU

**Comment by kermitt2** [comment]
I don't think it's possible to train a model using ELMo without GPU. I have never tested ELMo without GPU actually (I am travelling right now, so I can't test). Do you have the same memory problem just using GloVe 300d and without ELMo?

**Comment by HaniehP** [comment]
I have been able to train an NER model with conll2003 using ELMo on a CPU with 180GB RAM. But, I have the memory problem when running it on a GPU with 16GB RAM.
The memory problem does not appear just using GloVe300d.

**Comment by HaniehP** [comment]
For me, I solve this issue by running the code for the first time to create .mdb files. The program will terminate (due to out of memory problem) after saving .mdb files successfully. The next time I run it, it works perfectly.
