### ISSUE TITLE
How should I cite your blog?

### ISSUE THREAD

**Issue by Das-Boot** [kermitt2/delft#24]
Nice work! Your work and blog 

> A reproducibility study on neural NER

 really helped my research, and I want to cite you blog in my research paper. Can you give me an example BibTeX entry? Just like Keras:

@misc{chollet2015keras,
  title={Keras},
  author={Chollet, Fran\c{c}ois and others},
  year={2015},
  howpublished={\url{https://keras.io}},
}

**Comment by kermitt2** [comment]
Hello @Das-Boot !

Thank you for your kind words. 

The following should be a decent BibTex formatting for the blog entry.

```bibtex
@misc{Lopez:2018a,
	author = {Patrice Lopez},
	title = {A reproducibility study on neural {NER}},
	publisher = {science-miner},
	type = {Blog},
	number = {September},
	year = {2018},
	note = {[Online; accessed Feb. 24, 2019]},
	howpublished = {\url{http://science-miner.com/a-reproducibility-study-on-neural-ner/}}
}
```

**Comment by Das-Boot** [comment]
So thanks!
