### ISSUE TITLE
Training of elmo embeddings

### ISSUE THREAD

**Issue by ashim95** [kermitt2/delft#3]
This might not be right place to ask, sorry for that. 

I see that you trained a 5.5B token elmo model. I am facing some problems training my own elmo model. Could you be kind enough to answer a few questions?

1. How long did it take you to train your own elmo model for 5.5B tokens? (How many GPUs?)

2. What was the size of each training file that you split the data into? My kernel kills the process with around 1 million lines per file. 

Thank You,

**Comment by kermitt2** [comment]
Hello! 

I didn't train it - the 5.5B ELMo embeddings have been trained by the AllenNLP team too, see the listed pre-trained ELMo Models [here](https://allennlp.org/elmo). 

About training new ELMo models, I am interested to train a model for French - I just started some tests for English with a single GTX 1080Ti and with much smaller train parts than yours and it failed quickly with OOM - so now I am trying to get more GPU to resume the tests...
