### ISSUE TITLE
Missing wikipedia-and-pmc embeddings location in starting guide

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/delft#30]
Hey, I've tried to run delft, I've configured the embeddings (it worked previously) but latest changes introduced new embeddings for which I did not find the source: 

```
Compiling embeddings... (this is done only one time per embeddings at first launch)
[...]
FileNotFoundError: [Errno 2] No such file or directory: '/media/lopez/T5/embeddings/wikipedia-pubmed-and-PMC-w2v.vec'
```

I guess they are from here? http://evexdb.org/pmresources/vec-space-models/

**Comment by kermitt2** [comment]
Hello !! Yes, this is correct, that's the embeddings for `word2vec-pmc`. It's just that I forget to put back `glove-840B` after testing the PMC word2vec (which are better indeed for scientific content)...

**Comment by lfoppiano** [comment]
ok so I should not use it, right? Cause I'm downloading it and it takes ages 😄

**Comment by kermitt2** [comment]
If you process some scientific articles, you can test them yes! a bit better than gloves for that sort of content if I remember well.

**Comment by lfoppiano** [comment]
OK

**Comment by kermitt2** [comment]
but you would need to retrain the existing models, they have been trained with gloves ... (this is visible in their config files)

**Comment by lfoppiano** [comment]
to disable the word2vec-pmc should I just remove the entry from the registry?

**Comment by kermitt2** [comment]
just replace `word2vec-pmc` as selected embeddings by `glove-840B` in `./grobidTagger.py`, line 172... but I just push this change.

**Comment by lfoppiano** [comment]
ah ok 
thanks
