### ISSUE TITLE
Tag for v0.2.3 missing

### ISSUE THREAD

**Issue by de-code** [kermitt2/delft#38]
To be able to refer to / download a particular release, it would be helpful to have a GitHub tag for each release version (as you have for GROBID) (or now at least the last release).

**Comment by lfoppiano** [comment]
It should be there now: https://github.com/kermitt2/delft/tree/v0.2.3 

If needed I can add more tags to the main releases, just let me know

**Comment by de-code** [comment]
Great, thank you!
