### ISSUE TITLE
How to convert GROBID training dataset to DeLFT GROBID training dataset?

### ISSUE THREAD

**Issue by de-code** [kermitt2/delft#43]
Hi @kermitt2 

The DeLFT GROBID training dataset has the label as the last column whereas the dataset in GROBID doesn't. I am guessing that is coming out of the alignment with the TEI files.
How do you generate the files with the label at the end?
Is there a command for that?

**Comment by kermitt2** [comment]
Hello again Daniel! 

In GROBID the training data is created at training time by combing the "raw" feature file (with token + features but without label) with the TEI files (which provide token + label). Final training format have token + features + label. 

The motivation is that we typically want to change the labeling in the TEI files without regenerating the feature file which implies to have the PDF files for generating the features. There are so many PDF files used for the training, it would be impossible to add that to the git project and usually we don't need to regenerate the features, only fix some labeling issues. 

For the GROBID models, DeLFT uses the token + features + label format (although as you noted, the features are not used for the moment). To get this file, you need to launch a traning in GROBID, for instance:

> ./gradlew train_header

You will see right at the beginning a temporary file generated with an extension `.train` (name is randomly generated).
If there is an evaluation also done with a random train/eval split, there will be also a `.eval` file. You can just interrupt the training and copy this `.train` file to be used with DeLFT.

**Comment by de-code** [comment]
> In GROBID the training data is created at training time by combing the "raw" feature file (with token + features but without label) with the TEI files (which provide token + label). Final training format have token + features + label.
> 
> The motivation is that we typically want to change the labeling in the TEI files without regenerating the feature file which implies to have the PDF files for generating the features. There are so many PDF files used for the training, it would be impossible to add that to the git project and usually we don't need to regenerate the features, only fix some labeling issues.

Keeping the labels separate from the automatically extracted features makes perfect sense to me. I wonder whether it would make sense if the TEI also included positional information / coordinates to not have to rely on the extraction order. But that is probably another topic.

> For the GROBID models, DeLFT uses the token + features + label format (although as you noted, the features are not used for the moment). To get this file, you need to launch a traning in GROBID, for instance:
> 
> > ./gradlew train_header
> 
> You will see right at the beginning a temporary file generated with an extension `.train` (name is randomly generated).
> If there is an evaluation also done with a random train/eval split, there will be also a `.eval` file. You can just interrupt the training and copy this `.train` file to be used with DeLFT.

Thank you, that worked. It also better highlights what the actual label will be (and something you explained to me, how text without a label should have a `note` element to not get a "random" label).
