### ISSUE TITLE
Average precision/recall/f1 per label

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/delft#47]
I've noticed that in the evaluation using n-fold crossvalidation, the report provides average precision/recall/f1 globally but not average scores by label. 

Could that be useful if I implement it? otherwise I will just compute them manually.

**Comment by kermitt2** [comment]
Hi Luca !
Yes that's definitively something missing. It would be a useful addition.

**Comment by kermitt2** [comment]
Added with PR #59
