### ISSUE TITLE
reader.py misses the the <EX_ENAMEX> annotated entities on LeMonde Corpus

### ISSUE THREAD

**Issue by pjox** [kermitt2/delft#61]
Hello,

I recently found that the `reader.py` script does not parse the entities annotated on the French corpus LeMonde annotated as  `<EX_ENAMEX>`, meaning that it misses some entities and also that it cuts some sentences as it ignores the text inside the tags.

This should not have a big impact as the number of entities annotated like this is rather little, but still it would be nice to patch the little bug. 😄 

Thanks!

**Comment by kermitt2** [comment]
Thank you @pjox !

This has been fixed by commit 838ea3584006d6e22f59b7fa314675048bb8826a in branch `bert-sequence-labeling` and it will be in master when the branch will be merged...

**Comment by kermitt2** [comment]
in PR #78

**Comment by kermitt2** [comment]
merged...
