### ISSUE TITLE
Be able to pass an additional callbacks argument to the train method of Sequence/Classifier object

### ISSUE THREAD

**Issue by oterrier** [kermitt2/delft#67]
It would be super useful in particular when you use delft as a library and want to implement a progress indicator during the training phase.

In practicle it could be:

`def train(self, x_train, y_train, x_valid=None, y_valid=None, callbacks=None)`

 callbacks should be a list of valid Keras callbacks and be propagated to the underlying Trainer object and then concateneted to the already defined delft callbacks before calling the fit() method of the Keras object

**Comment by lfoppiano** [comment]
I guess this is also solved with #75 ?

**Comment by oterrier** [comment]
Yes, the ticket can be closed
Merry Xmas

Le lun. 23 déc. 2019 à 16:26, Luca Foppiano <notifications@github.com> a
écrit :

**Comment by lfoppiano** [comment]
🎄 Merry Xmas! 😄
