### ISSUE TITLE
sequenceLabelling.Trainer.train method fails if validation set is None

### ISSUE THREAD

**Issue by bfreuden** [kermitt2/delft#69]
There are some problems with the trainer itself (during the concatenation of the training and validation sets), with the data_generator (unable to compute its len), and with the on_epoch_end of the trainer (assuming validation is not empty).
I will submit a PR today.

**Comment by lfoppiano** [comment]
I think this was also solved with #70, correct?

**Comment by bfreuden** [comment]
@lfoppiano yes it is. 
I'm sorry: next time I'll put the bug number in the commit message.

**Comment by lfoppiano** [comment]
@bfreuden don't worry I was pretty sure it was the same but I didn't want to close it too eagerly :-)
