### ISSUE TITLE
new multiprocessing parameter for Sequence and TrainingConfig

### ISSUE THREAD

**Issue by bfreuden** [kermitt2/delft#71]
There are some reports of multiprocessing causing locking problems (with Keras hanging forever):
https://github.com/keras-team/keras/issues/3181
https://github.com/keras-team/keras/issues/10340
https://github.com/keras-team/keras/issues/9964
We encountered this problem when training sequence labelling without ELMo (where multiprocessing is disabled by Delft). To be honest it might be caused by some gloomy Python process fork, but I'm not able to find out why we're having this problem.
Having the possibility to disable multiprocessing would be great.

I will submit a PR today.

**Comment by kermitt2** [comment]
Thank you @bfreuden, it's nice to have such a parameter in general (on my side, I've not seen this problem without ELMo).

**Comment by bfreuden** [comment]
You're very welcome. We don't have the problem neither when running Delft in command-line. However  the problem arises when running Delft in a Python web framework (gunicorn).

**Comment by lfoppiano** [comment]
Is this solved with PR #72 ?

**Comment by bfreuden** [comment]
@lfoppiano yes, that's it

**Comment by lfoppiano** [comment]
👍
