### ISSUE TITLE
header training data -  mismatching features columns? 

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/delft#81]
I've been testing the header model training data using features #76  and I've incurred in one small problem, it seems that the number of columns are not consistent. 

For example: 
'anaesthesia' on line 938 and 'elsevier', line 813 have different number of columns (30 vs 31): 

```ELSEVIER elsevier E EL ELS ELSE R ER IER VIER BLOCKSTART LINESTART NEWFONT HIGHERFONT 0 0 0 ALLCAP NODIGIT 0 0 0 0 0 0 0 0 0 0 NOPUNCT 0 0 I-<note>```

```Anaesthesia anaesthesia A An Ana Anae a ia sia esia BLOCKSTART LINESTART LINEINDENT NEWFONT HIGHERFONT 0 0 0 INITCAP NODIGIT 0 0 1 0 0 0 0 0 NOPUNCT 0 0 <reference>```

I'm not sure is a bug (at least not in the current version - which is ignoring these information), and also I'm not sure this is the right place, but training the header model will fail with the automatic feature discovery enabled

**Comment by kermitt2** [comment]
Hello ! The first line is a feature input for the header model, the second one is the features for the Reference Segmenter model.  
So it seems that there are some mixture between the two training data, it comes from GROBID I think.

**Comment by lfoppiano** [comment]
> Hello ! The first line is a feature input for the header model, the second one is the features for the Reference Segmenter model.
> So it seems that there are some mixture between the two training data, it comes from GROBID I think.

are you sure it's the segmenter? I've run a quick check, it seems that `<reference>` is a valid header tag while the segmentation model has a tag called `<references>`. 

I've made an analysis on the header data and added here: https://github.com/kermitt2/grobid/issues/531

**Comment by kermitt2** [comment]
yes reference-segmenter model (not segmentation). No clue how some of these features arrived there! The features are combined with the header labels in a late stage, so the labels are not a good hint.

**Comment by lfoppiano** [comment]
Here I found a similar problem with the tables: 

- 23 items: 
```
Table table T Ta Tab Tabl e le ble able BLOCKSTART LINESTART ALIGNEDLEFT SAMEFONT SAMEFONTSIZE 0 0 INITCAP NODIGIT 0 NOPUNCT 10 1 0 I-<figure_head>
7 7 7 7 7 7 7 7 7 7 BLOCKIN LINEIN ALIGNEDLEFT SAMEFONT SAMEFONTSIZE 0 0 NOCAPS ALLDIGIT 1 NOPUNCT 10 1 0 I-<label>
: : : : : : : : : : BLOCKIN LINEIN ALIGNEDLEFT SAMEFONT SAMEFONTSIZE 0 0 ALLCAP NODIGIT 1 PUNCT 10 1 0 I-<figure_head>
Asymptotic asymptotic A As Asy Asym c ic tic otic BLOCKIN LINEIN ALIGNEDLEFT SAMEFONT SAMEFONTSIZE 0 0 INITCAP NODIGIT 0 NOPUNCT 10 1 0 I-<content>
confidence confidence c co con conf e ce nce ence BLOCKIN LINEIN ALIGNEDLEFT SAMEFONT SAMEFONTSIZE 0 0 NOCAPS NODIGIT 0 NOPUNCT 10 1 0 <content>
intervals intervals i in int inte s ls als vals BLOCKIN LINEIN ALIGNEDLEFT SAMEFONT SAMEFONTSIZE 0 0 NOCAPS NODIGIT 0 NOPUNCT 10 1 0 <content>
```

and this one, with 24 items: 
```
TABLE table T TA TAB TABL E LE BLE ABLE BLOCKSTART LINESTART LINEINDENT SAMEFONT SAMEFONTSIZE 0 0 ALLCAP NODIGIT 0 NOPUNCT 7 10 0 1 I-<figure_head>
IV iv I IV IV IV V IV IV IV BLOCKIN LINEIN LINEINDENT SAMEFONT SAMEFONTSIZE 0 0 ALLCAP NODIGIT 0 NOPUNCT 7 10 0 1 I-<label>
. . . . . . . . . . BLOCKIN LINEIN LINEINDENT SAMEFONT SAMEFONTSIZE 0 0 ALLCAP NODIGIT 1 DOT 7 10 0 1 I-<figure_head>
SNR snr S SN SNR SNR R NR SNR SNR BLOCKIN LINEIN LINEINDENT SAMEFONT SAMEFONTSIZE 0 0 ALLCAP NODIGIT 0 NOPUNCT 7 10 0 1 <figure_head>
IN in I IN IN IN N IN IN IN BLOCKIN LINEIN LINEINDENT SAMEFONT LOWERFONT 0 0 ALLCAP NODIGIT 0 NOPUNCT 7 10 0 1 <figure_head>
dB db d dB dB dB B dB dB dB BLOCKIN LINEIN LINEINDENT SAMEFONT HIGHERFONT 0 0 NOCAPS NODIGIT 0 NOPUNCT 7 10 0 1 <figure_head>
FOR for F FO FOR FOR R OR FOR FOR BLOCKIN LINEIN LINEINDENT SAMEFONT LOWERFONT 0 0 ALLCAP NODIGIT 0 NOPUNCT 7 10 0 1 <figure_head>
EACH each E EA EAC EACH H CH ACH EACH BLOCKIN LINEIN LINEINDENT SAMEFONT SAMEFONTSIZE 0 0 ALLCAP NODIGIT 0 NOPUNCT 7 10 0 1 <figure_head>
TELESCOPE telescope T TE TEL TELE E PE OPE COPE BLOCKIN LINEIN LINEINDENT SAMEFONT SAMEFONTSIZE 0 0 ALLCAP NODIGIT 0 NOPUNCT 7 10 0 1 <figure_head>
AND and A AN AND AND D ND AND AND BLOCKIN LINEIN LINEINDENT SAMEFONT SAMEFONTSIZE 0 0 ALLCAP NODIGIT 0 NOPUNCT 7 10 0 1 <figure_head>
SCENARIO scenario S SC SCE SCEN O IO RIO ARIO BLOCKIN LINEIN LINEINDENT SAMEFONT SAMEFONTSIZE 0 0 ALLCAP NODIGIT 0 NOPUNCT 7 10 0 1 <figure_head>
, , , , , , , , , , BLOCKIN LINEIN LINEINDENT SAMEFONT SAMEFONTSIZE 0 0 ALLCAP NODIGIT 1 COMMA 7 10 0 1 <figure_head>
INCLUDING including I IN INC INCL G NG ING DING BLOCKIN LINEEND LINEINDENT SAMEFONT SAMEFONTSIZE 0 0 ALLCAP NODIGIT 0 NOPUNCT 7 10 0 1 <figure_head>
```

if I calculate the lengths of the different examples they are quite mixed up (this is the length of the first token of each example: 

```
[24, 23, 23, 24, 23, 24, 24, 24, 24, 23, 23, 24, 30, 23, 24, 23, 24, 23, 23, 23, 23, 23, 23, 23, 24, 24, 23, 24, 23, 24, 23, 24, 23, 23, 30, 24, 24, 23, 23, 24, 23, 24, 24, 23, 23, 24, 24, 24, 23, 23, 24, 23]
```

**Comment by kermitt2** [comment]
I've updated the training data for the table model (and figure model) with commit 37eaa431a8c4bf273bd961a4120eda3911093cd0

**Comment by lfoppiano** [comment]
@kermitt2 thanks! I will check today.
