### ISSUE TITLE
Suggestion: save preprocessor in a more transferable format

### ISSUE THREAD

**Issue by de-code** [kermitt2/delft#91]
The pickle format is meant mainly for short term storage.

It comes with a few drawbacks:
- ["The pickle module is not secure."](https://docs.python.org/3/library/pickle.html)
- It ties the model to the current implementation: refactoring the code or upgrading a library might break unpickling
- It's Python only and opaque: it would be difficult to use a trained model and serve it separately 

/cc @kermitt2 @lfoppiano

**Comment by lfoppiano** [comment]
@de-code do you have any suggestions?

**Comment by kermitt2** [comment]
Thank you @de-code I agree, I had already several times problems when modifying the code which broke compatibility of the existing pickle preprocessor - and it will happen again when adding the feature preprocessor. We could probably simply save the data in json because it's only a few maps.

**Comment by lfoppiano** [comment]
What about saving everything in the `config.json`? Or should be in a separate file?

**Comment by kermitt2** [comment]
I think it would make the config.json hard to read because the different saved vocab maps can be a bit large. Another discussion we had was to use the config.json file as a way to parameter a training instead of passing arguments, so that would make sense to separate the model preprocessor data.

**Comment by de-code** [comment]
`json` sounds good. I often reduce the size by gzip compressing slightly larger files and there is usually good support for gzip.

**Comment by lfoppiano** [comment]
I forgot to link it to PR #105, I guess we could close this issue.

**Comment by kermitt2** [comment]
yes !
